*Series and DataFrame

In [3]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes(as_frame = True)
print(type(diabetes['data']))

<class 'pandas.DataFrame'>

In [4]:
df = diabetes["data"]
df

          age       sex       bmi  ...        s4        s5        s6
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [7]:
import pandas as pd 
cities = pd.Series(["chennai","bangalore","hyderbed","Delhi"])
population = pd.Series([1500000,1700000,1400000])

city_info = pd.DataFrame({"cities" : cities,"population":population})
city_info

      cities  population
0    chennai   1500000.0
1  bangalore   1700000.0
2   hyderbed   1400000.0
3      Delhi         NaN

In [9]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

                age           sex  ...            s5            s6
count  4.420000e+02  4.420000e+02  ...  4.420000e+02  4.420000e+02
mean  -2.511817e-19  1.230790e-17  ...  9.268604e-17  1.130318e-17
std    4.761905e-02  4.761905e-02  ...  4.761905e-02  4.761905e-02
min   -1.072256e-01 -4.464164e-02  ... -1.260971e-01 -1.377672e-01
25%   -3.729927e-02 -4.464164e-02  ... -3.324559e-02 -3.317903e-02
50%    5.383060e-03 -4.464164e-02  ... -1.947171e-03 -1.077698e-03
75%    3.807591e-02  5.068012e-02  ...  3.243232e-02  2.791705e-02
max    1.107267e-01  5.068012e-02  ...  1.335973e-01  1.356118e-01

[8 rows x 10 columns]

In [11]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='str')

In [14]:
df['age'][:5]

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
Name: age, dtype: float64

In [15]:
df['age'][:-5]

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...
432    0.009016
433   -0.027310
434    0.016281
435   -0.012780
436   -0.056370
Name: age, Length: 437, dtype: float64

In [16]:
df['age'][-5:]

437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, dtype: float64

In [17]:
df['age'][100:150]

100    0.016281
101    0.016281
102   -0.092695
103    0.059871
104   -0.027310
105    0.023546
106   -0.096328
107    0.027178
108    0.019913
109    0.038076
110    0.041708
111    0.019913
112   -0.085430
113    0.019913
114    0.023546
115   -0.030942
116    0.048974
117    0.059871
118   -0.056370
119    0.016281
120   -0.049105
121    0.063504
122    0.048974
123    0.005383
124   -0.005515
125   -0.005515
126   -0.089063
127    0.034443
128   -0.052738
129    0.009016
130   -0.063635
131   -0.096328
132    0.016281
133   -0.041840
134   -0.074533
135   -0.005515
136   -0.092695
137    0.005383
138    0.034443
139    0.023546
140    0.041708
141   -0.027310
142    0.041708
143   -0.030942
144    0.030811
145   -0.041840
146   -0.030942
147   -0.056370
148   -0.060003
149   -0.049105
Name: age, dtype: float64

In [20]:
df[['age','sex']]

          age       sex
0    0.038076  0.050680
1   -0.001882 -0.044642
2    0.085299  0.050680
3   -0.089063 -0.044642
4    0.005383 -0.044642
..        ...       ...
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

[442 rows x 2 columns]

In [21]:
df[['age','sex']][:5]

        age       sex
0  0.038076  0.050680
1 -0.001882 -0.044642
2  0.085299  0.050680
3 -0.089063 -0.044642
4  0.005383 -0.044642

In [ ]:
# Integer position
df.iloc[0]

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [ ]:
# series number position [0,1,2,3,4]
df.loc[0]

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [24]:
df.head()

        age       sex       bmi  ...        s4        s5        s6
0  0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1 -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2  0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3 -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4  0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641

[5 rows x 10 columns]

In [28]:
df.loc[4,'age']

np.float64(0.005383060374248237)

In [30]:
df.iloc[4,0:5]

age    0.005383
sex   -0.044642
bmi   -0.036385
bp     0.021872
s1     0.003935
Name: 4, dtype: float64

In [31]:
df.loc[df.age< 5]

          age       sex       bmi  ...        s4        s5        s6
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [70]:
import pandas as pd 
import numpy as np

df = pd.DataFrame(np.random.rand(9,4), index=list("abcdefghi"),columns=list("ABDE"))
df
df.shape

(9, 4)

In [44]:
another_df = pd.DataFrame(
    np.random.rand(100,4),
    index = range(10,110),
    columns=list("ABCD")
)
another_df

            A         B         C         D
10   0.259543  0.030700  0.596045  0.831052
11   0.986896  0.323019  0.511808  0.691841
12   0.061347  0.469009  0.743728  0.278349
13   0.143075  0.293345  0.567037  0.393965
14   0.794181  0.766097  0.817578  0.669993
..        ...       ...       ...       ...
105  0.217852  0.138484  0.495763  0.806369
106  0.282347  0.505513  0.506553  0.233108
107  0.027136  0.878079  0.087833  0.630629
108  0.396989  0.290376  0.397199  0.109448
109  0.516227  0.234851  0.695968  0.556580

[100 rows x 4 columns]

In [49]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='str')

In [50]:
df.loc['a']

A    0.694583
S    0.528426
D    0.844549
E    0.909182
Name: a, dtype: float64

In [ ]:
df.loc['a', 'B':'D']

S    0.528426
D    0.844549
Name: a, dtype: float64

In [57]:
df.loc['a':'b',:]

          A         S         D         E
a  0.694583  0.528426  0.844549  0.909182
b  0.003089  0.636401  0.671979  0.559629

In [58]:
df.iloc[:4,:]

          A         S         D         E
a  0.694583  0.528426  0.844549  0.909182
b  0.003089  0.636401  0.671979  0.559629
c  0.565112  0.317574  0.547597  0.312114
d  0.627793  0.048010  0.330897  0.727450

In [61]:
df.iloc[:4,1:3]

          S         D
a  0.528426  0.844549
b  0.636401  0.671979
c  0.317574  0.547597
d  0.048010  0.330897

In [66]:
selector = lambda df: df["A"]>0.5
selector

In [67]:
df.loc[selector]

          A         S         D         E
a  0.694583  0.528426  0.844549  0.909182
c  0.565112  0.317574  0.547597  0.312114
d  0.627793  0.048010  0.330897  0.727450
f  0.540171  0.242585  0.434748  0.358805
g  0.810172  0.441003  0.257868  0.904393
i  0.894390  0.320386  0.418679  0.079702

In [72]:
condition_for_evalution = (df['A']>0.5) & (df['B']<0.2)
condition_for_evalution

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i     True
dtype: bool

In [74]:
df[condition_for_evalution]

          A         B         D        E
i  0.858015  0.023104  0.509065  0.58929

In [75]:
df['E']= df['A']*100
df

          A         B         D          E
a  0.195862  0.326342  0.860448  19.586219
b  0.581490  0.841268  0.792175  58.148963
c  0.069690  0.419593  0.271775   6.968963
d  0.324034  0.524592  0.805047  32.403380
e  0.252600  0.416743  0.404814  25.259974
f  0.232266  0.692322  0.840566  23.226575
g  0.178472  0.764171  0.295854  17.847214
h  0.280340  0.829828  0.405096  28.033984
i  0.858015  0.023104  0.509065  85.801484

In [77]:
df['C']= df['A']*4
df

          A         B         D          E         C
a  0.195862  0.326342  0.587587  19.586219  0.783449
b  0.581490  0.841268  1.744469  58.148963  2.325959
c  0.069690  0.419593  0.209069   6.968963  0.278759
d  0.324034  0.524592  0.972101  32.403380  1.296135
e  0.252600  0.416743  0.757799  25.259974  1.010399
f  0.232266  0.692322  0.696797  23.226575  0.929063
g  0.178472  0.764171  0.535416  17.847214  0.713889
h  0.280340  0.829828  0.841020  28.033984  1.121359
i  0.858015  0.023104  2.574045  85.801484  3.432059

In [78]:
df['F'] = df['A']+df['B']
df

          A         B         D          E         C         F
a  0.195862  0.326342  0.587587  19.586219  0.783449  0.522204
b  0.581490  0.841268  1.744469  58.148963  2.325959  1.422758
c  0.069690  0.419593  0.209069   6.968963  0.278759  0.489283
d  0.324034  0.524592  0.972101  32.403380  1.296135  0.848626
e  0.252600  0.416743  0.757799  25.259974  1.010399  0.669342
f  0.232266  0.692322  0.696797  23.226575  0.929063  0.924588
g  0.178472  0.764171  0.535416  17.847214  0.713889  0.942643
h  0.280340  0.829828  0.841020  28.033984  1.121359  1.110168
i  0.858015  0.023104  2.574045  85.801484  3.432059  0.881119

In [79]:
criteria = df['A'] < 0.2
criteria

a     True
b    False
c     True
d    False
e    False
f    False
g     True
h    False
i    False
Name: A, dtype: bool

In [80]:
df.loc[criteria ,'A'] = 0
df

          A         B         D          E         C         F
a  0.000000  0.326342  0.587587  19.586219  0.783449  0.522204
b  0.581490  0.841268  1.744469  58.148963  2.325959  1.422758
c  0.000000  0.419593  0.209069   6.968963  0.278759  0.489283
d  0.324034  0.524592  0.972101  32.403380  1.296135  0.848626
e  0.252600  0.416743  0.757799  25.259974  1.010399  0.669342
f  0.232266  0.692322  0.696797  23.226575  0.929063  0.924588
g  0.000000  0.764171  0.535416  17.847214  0.713889  0.942643
h  0.280340  0.829828  0.841020  28.033984  1.121359  1.110168
i  0.858015  0.023104  2.574045  85.801484  3.432059  0.881119

In [82]:
df['City'] =['Chennai','Madurai','Cbe','Trichy','Chennai','Madurai','Cbe','Trichy','chennai']
df

          A         B         D          E         C         F     City
a  0.000000  0.326342  0.587587  19.586219  0.783449  0.522204  Chennai
b  0.581490  0.841268  1.744469  58.148963  2.325959  1.422758  Madurai
c  0.000000  0.419593  0.209069   6.968963  0.278759  0.489283      Cbe
d  0.324034  0.524592  0.972101  32.403380  1.296135  0.848626   Trichy
e  0.252600  0.416743  0.757799  25.259974  1.010399  0.669342  Chennai
f  0.232266  0.692322  0.696797  23.226575  0.929063  0.924588  Madurai
g  0.000000  0.764171  0.535416  17.847214  0.713889  0.942643      Cbe
h  0.280340  0.829828  0.841020  28.033984  1.121359  1.110168   Trichy
i  0.858015  0.023104  2.574045  85.801484  3.432059  0.881119  chennai

In [89]:
df['Copy'] = df['City']
df

          A         B         D  ...         F     City     Copy
a  0.000000  0.326342  0.587587  ...  0.522204  Chennai  Chennai
b  0.581490  0.841268  1.744469  ...  1.422758  Madurai  Madurai
c  0.000000  0.419593  0.209069  ...  0.489283      Cbe      Cbe
d  0.324034  0.524592  0.972101  ...  0.848626   Trichy   Trichy
e  0.252600  0.416743  0.757799  ...  0.669342  Chennai  Chennai
f  0.232266  0.692322  0.696797  ...  0.924588  Madurai  Madurai
g  0.000000  0.764171  0.535416  ...  0.942643      Cbe      Cbe
h  0.280340  0.829828  0.841020  ...  1.110168   Trichy   Trichy
i  0.858015  0.023104  2.574045  ...  0.881119  chennai  chennai

[9 rows x 8 columns]

In [94]:
checking = df['City'].isin(["Chennai"])
checking

a     True
b    False
c    False
d    False
e     True
f    False
g    False
h    False
i    False
Name: City, dtype: bool

#Aggregation and Grouping

In [95]:
random_state = np.random.RandomState(42)
random_series = pd.Series(random_state.rand(10))
random_series

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
5    0.155995
6    0.058084
7    0.866176
8    0.601115
9    0.708073
dtype: float64

In [96]:
random_series.mean()

np.float64(0.5201367359526748)

In [97]:
random_series.std()

np.float64(0.3158656227180549)

In [98]:
random_series.sum()

np.float64(5.201367359526748)

In [99]:
df= pd.DataFrame({'A': random_state.rand(5),
                  'B': random_state.rand(5),
                  'C': random_state.rand(5)})

df

          A         B         C
0  0.020584  0.183405  0.611853
1  0.969910  0.304242  0.139494
2  0.832443  0.524756  0.292145
3  0.212339  0.431945  0.366362
4  0.181825  0.291229  0.456070

In [105]:
#column vise 
stats = df.mean()
stats

A    0.443420
B    0.347115
C    0.373185
dtype: float64

In [106]:
#row vise 
df.mean(axis=1)

0    0.271947
1    0.471215
2    0.549781
3    0.336882
4    0.309708
dtype: float64

#Group By 

split
combine 
Apply

In [111]:
df = pd.DataFrame({'Key': ['A','B','C']*2,
                   'data': range(6)})
df

  Key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [113]:
df.groupby("Key")

In [114]:
df.groupby("Key").sum()

     data
Key
A       3
B       5
C       7